# Generated by Django 5.0.1 on 2025-10-19 11:11

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Restaurant name", max_length=200, verbose_name="name"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Restaurant description",
                        verbose_name="description",
                    ),
                ),
                (
                    "cuisine_type",
                    models.CharField(
                        choices=[
                            ("italian", "Итальянская"),
                            ("japanese", "Японская"),
                            ("chinese", "Китайская"),
                            ("french", "Французская"),
                            ("mexican", "Мексиканская"),
                            ("indian", "Индийская"),
                            ("thai", "Тайская"),
                            ("american", "Американская"),
                            ("mediterranean", "Средиземноморская"),
                            ("russian", "Русская"),
                            ("georgian", "Грузинская"),
                            ("other", "Другая"),
                        ],
                        help_text="Type of cuisine",
                        max_length=20,
                        verbose_name="cuisine type",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        help_text="Contact phone number",
                        max_length=128,
                        region=None,
                        verbose_name="phone number",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Contact email", max_length=254, verbose_name="email"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="Full address", max_length=500, verbose_name="address"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="City", max_length=100, verbose_name="city"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitude coordinate",
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitude coordinate",
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                        verbose_name="longitude",
                    ),
                ),
                (
                    "opening_time",
                    models.TimeField(
                        help_text="Restaurant opening time", verbose_name="opening time"
                    ),
                ),
                (
                    "closing_time",
                    models.TimeField(
                        help_text="Restaurant closing time", verbose_name="closing time"
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Average rating (0-5)",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="average rating",
                    ),
                ),
                (
                    "total_reviews",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of reviews",
                        verbose_name="total reviews",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is restaurant active and accepting reservations",
                        verbose_name="active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "restaurant",
                "verbose_name_plural": "restaurants",
                "ordering": ["-average_rating", "name"],
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "table_number",
                    models.CharField(
                        help_text="Table number or identifier",
                        max_length=20,
                        verbose_name="table number",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        help_text="Maximum number of guests",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="capacity",
                    ),
                ),
                (
                    "location_in_restaurant",
                    models.CharField(
                        choices=[
                            ("main_hall", "Основной зал"),
                            ("terrace", "Терраса"),
                            ("vip_room", "VIP зал"),
                            ("bar", "Барная зона"),
                            ("window", "У окна"),
                        ],
                        default="main_hall",
                        help_text="Location of table in restaurant",
                        max_length=20,
                        verbose_name="location",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Is table available for reservations",
                        verbose_name="available",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "table",
                "verbose_name_plural": "tables",
                "ordering": ["restaurant", "table_number"],
            },
        ),
    ]
