# Generated by Django 5.0.1 on 2025-10-19 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="owner",
            field=models.ForeignKey(
                help_text="Restaurant owner",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_restaurants",
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner",
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="restaurant",
            field=models.ForeignKey(
                help_text="Restaurant this table belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tables",
                to="restaurants.restaurant",
                verbose_name="restaurant",
            ),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(fields=["city"], name="restaurants_city_6db275_idx"),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(
                fields=["cuisine_type"], name="restaurants_cuisine_01615e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(fields=["owner"], name="restaurants_owner_i_a6fa17_idx"),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(
                fields=["average_rating"], name="restaurants_average_ec7bf2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(
                fields=["is_active"], name="restaurants_is_acti_38f6bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(
                fields=["created_at"], name="restaurants_created_b77db1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="table",
            index=models.Index(
                fields=["restaurant"], name="restaurants_restaur_d61f4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="table",
            index=models.Index(
                fields=["capacity"], name="restaurants_capacit_590580_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="table",
            index=models.Index(
                fields=["is_available"], name="restaurants_is_avai_9e5eb7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="table",
            unique_together={("restaurant", "table_number")},
        ),
    ]
