# Generated by Django 5.0.1 on 2025-10-19 20:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Dish name", max_length=200, verbose_name="name"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Dish description",
                        verbose_name="description",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("appetizer", "Закуски"),
                            ("soup", "Супы"),
                            ("salad", "Салаты"),
                            ("main_course", "Основные блюда"),
                            ("dessert", "Десерты"),
                            ("beverage", "Напитки"),
                            ("alcohol", "Алкоголь"),
                            ("other", "Другое"),
                        ],
                        help_text="Dish category",
                        max_length=20,
                        verbose_name="category",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Dish price",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="price",
                    ),
                ),
                (
                    "preparation_time",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Preparation time in minutes",
                        null=True,
                        verbose_name="preparation time",
                    ),
                ),
                (
                    "is_vegetarian",
                    models.BooleanField(
                        default=False,
                        help_text="Is dish vegetarian",
                        verbose_name="vegetarian",
                    ),
                ),
                (
                    "is_vegan",
                    models.BooleanField(
                        default=False, help_text="Is dish vegan", verbose_name="vegan"
                    ),
                ),
                (
                    "is_gluten_free",
                    models.BooleanField(
                        default=False,
                        help_text="Is dish gluten free",
                        verbose_name="gluten free",
                    ),
                ),
                (
                    "is_spicy",
                    models.BooleanField(
                        default=False, help_text="Is dish spicy", verbose_name="spicy"
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Is dish available for ordering",
                        verbose_name="available",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        help_text="Restaurant this dish belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dishes",
                        to="restaurants.restaurant",
                        verbose_name="restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "dish",
                "verbose_name_plural": "dishes",
                "ordering": ["restaurant", "category", "name"],
                "indexes": [
                    models.Index(
                        fields=["restaurant"], name="restaurants_restaur_df035b_idx"
                    ),
                    models.Index(
                        fields=["category"], name="restaurants_categor_b120db_idx"
                    ),
                    models.Index(fields=["price"], name="restaurants_price_446206_idx"),
                    models.Index(
                        fields=["is_available"], name="restaurants_is_avai_8ac1da_idx"
                    ),
                    models.Index(
                        fields=["is_vegetarian"], name="restaurants_is_vege_3a192c_idx"
                    ),
                    models.Index(
                        fields=["is_vegan"], name="restaurants_is_vega_d6d2b9_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="restaurants_created_19f3e3_idx"
                    ),
                ],
            },
        ),
    ]
