# Generated by Django 5.0.1 on 2025-10-19 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="Reservation date", verbose_name="date"),
                ),
                (
                    "time_slot",
                    models.TimeField(help_text="Reservation time", verbose_name="time"),
                ),
                (
                    "guests_count",
                    models.PositiveSmallIntegerField(
                        help_text="Number of guests",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="guests count",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("confirmed", "Подтверждено"),
                            ("seated", "Гость за столом"),
                            ("completed", "Завершено"),
                            ("cancelled", "Отменено"),
                            ("no_show", "Гость не пришёл"),
                        ],
                        default="pending",
                        help_text="Reservation status",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "special_requests",
                    models.TextField(
                        blank=True,
                        help_text="Special requests from guest (allergies, celebration, etc.)",
                        verbose_name="special requests",
                    ),
                ),
                (
                    "confirmation_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Was confirmation email sent",
                        verbose_name="confirmation sent",
                    ),
                ),
                (
                    "reminder_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Was reminder email sent",
                        verbose_name="reminder sent",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "reservation",
                "verbose_name_plural": "reservations",
                "ordering": ["-date", "-time_slot"],
            },
        ),
    ]
