# Generated by Django 5.0.1 on 2025-10-19 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reservations", "0001_initial"),
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="restaurant",
            field=models.ForeignKey(
                help_text="Restaurant for reservation",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="restaurants.restaurant",
                verbose_name="restaurant",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="table",
            field=models.ForeignKey(
                help_text="Reserved table",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="restaurants.table",
                verbose_name="table",
            ),
        ),
    ]
