# Generated by Django 5.0.1 on 2025-10-19 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reservations", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                help_text="User who made the reservation",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(fields=["user"], name="reservation_user_id_56b0f8_idx"),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["restaurant"], name="reservation_restaur_6780ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(fields=["table"], name="reservation_table_i_87de62_idx"),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(fields=["date"], name="reservation_date_d6d267_idx"),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(fields=["status"], name="reservation_status_f1a03a_idx"),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["date", "time_slot"], name="reservation_date_40c1cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["created_at"], name="reservation_created_fddb5a_idx"
            ),
        ),
    ]
